### ISSUE TITLE
Should we try to support bibliography cross-references between a supplement and a main document?

### ISSUE THREAD

**Issue by tgkolda** [tgkolda/siam-latex#10]
This is technically complicated enough that we currently require separate bibliographies.

**Comment by rjleveque** [comment]
I think separate bibliographies are fine.  Presumably the main document would not refer to a bibliography entry that's only in the supplement anyway, since if it's cited in the main doc it should appear in the main doc bibliography.  And space is not an issue for the supplement so it's ok if some references are repeated there to make it self-contained.

**Comment by tgkolda** [comment]
Doesn't seem to be possible, so closing.
