### ISSUE TITLE
Using a URL in thanks causes problems if it has a ~ character. 

### ISSUE THREAD

**Issue by tgkolda** [tgkolda/siam-latex#14]
This seems to be a function of the weirdness of how author names and thanks are processed. There is no problem with the same web page in the main body of the document.

 \url{{http://www.sandia.gov/~tgkolda/}

**Comment by JHainesSIAM** [comment]
If you precede the ~ with a \string command, the URL prints and links correctly:

\documentclass[final,leqno]{siamart} 
\urlstyle{same}
\title{My Title\thanks{I'm at \url{http://www.sandia.gov/\string~tgkolda/}.}}
\author{My Name\thanks{I'm at \url{http://www.sandia.gov/\string~tgkolda/}.}}
\begin{document}
\maketitle
\end{document}

It does seem to be a problem only inside a \thanks command.

Also, we add the \urlstyle{same} so that URLs print in the same font as the surrounding text. We’ve always been instructed to change the font from typewriter. I suppose that line could go somewhere in the class file now that I think about it.
